### ISSUE TITLE
Line 42 echo "Backup of database $DB failed."

### ISSUE THREAD

**Issue by ksthomas** [uberhacker/shrink-ibdata1#1]
Should be followed with an exit on the next line just in case the user did not know to change the username and password. Fortunately I had made my own backup before destroying my tablespace. 

Nice script though, thank you!

**Comment by uberhacker** [comment]
@ksthomas: Thank you for the feedback!  I have pushed a new commit with your suggestion along with a prompt for the password if it isn't correct.  I also noticed that the mysql service can be either `mysql` or `mysqld`, so I added the `MYSQL_SERVICE` variable to accommodate.
